//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_sms_site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public Nullable<int> user { get; set; }
        public Nullable<long> contact_number { get; set; }
        public string name { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual user_required user_required { get; set; }
    }
}
