//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_sms_site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class friend_list
    {
        public int Id { get; set; }
        public Nullable<int> sender_id { get; set; }
        public Nullable<int> receiver_id { get; set; }
        public string date_time { get; set; }
        public string status { get; set; }
        public Nullable<int> request_id { get; set; }
    
        public virtual user_required user_required { get; set; }
        public virtual Friend_Request Friend_Request { get; set; }
        public virtual user_required user_required1 { get; set; }
    }
}
