//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_sms_site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public string messages { get; set; }
        public Nullable<int> To { get; set; }
        public Nullable<int> From { get; set; }
        public Nullable<long> no_of_receiver { get; set; }
        public Nullable<long> no_of_sender { get; set; }
        public string date_time { get; set; }
        public string attachment { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual user_required user_required { get; set; }
        public virtual user_required user_required1 { get; set; }
    }
}
