//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_sms_site.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmsSite_dbEntities : DbContext
    {
        public SmsSite_dbEntities()
            : base("name=SmsSite_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<friend_list> friend_list { get; set; }
        public virtual DbSet<Friend_Request> Friend_Request { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<user_personal> user_personal { get; set; }
        public virtual DbSet<user_professional> user_professional { get; set; }
        public virtual DbSet<user_required> user_required { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<texting> texting { get; set; }
        public virtual DbSet<credit_card> credit_card { get; set; }
    }
}
