//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_sms_site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class texting
    {
        public int Id { get; set; }
        public Nullable<int> from { get; set; }
        public Nullable<long> to { get; set; }
        public string name_of_receiver { get; set; }
        public string time { get; set; }
        public string text { get; set; }
        public string status { get; set; }
    
        public virtual user_required user_required { get; set; }
    }
}
