//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_sms_site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_professional
    {
        public int S_No { get; set; }
        public int Id { get; set; }
        public string qualification { get; set; }
        public string school { get; set; }
        public string college { get; set; }
        public string work_status { get; set; }
        public string organization { get; set; }
        public string designation { get; set; }
    
        public virtual user_required user_required { get; set; }
    }
}
