//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_sms_site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_personal
    {
        public int S_No { get; set; }
        public int user_id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string DOB { get; set; }
        public string address { get; set; }
        public string status { get; set; }
        public string hobbies { get; set; }
        public string likes { get; set; }
        public string dislikes { get; set; }
        public string cuisines { get; set; }
        public string sports { get; set; }
        public string photo { get; set; }
    
        public virtual user_required user_required { get; set; }
    }
}
